/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CardConnect.java
 *
 * Created on Jun 5, 2010, 8:28:03 AM
 */

package Viewers.Cards;


/**
 *
 * @author Gerjo Meier
 */
public class CardConnect extends javax.swing.JPanel {
    Viewers.TabbedGUI owner = null;
    /** Creates new form CardConnect */

    public CardConnect(){
        initComponents();
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
    public CardConnect(Viewers.TabbedGUI owner) {
        this();
        this.owner = owner;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/button_connect_to_zeppelin_normal.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        showLoadingImage();
        new Thread(
            new Runnable() {
                public void run() {
                    owner.getMainController().getZeppelinController().connectToZeppelin();
                    showConnectedImage();
                }
            }
        ).start();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        //showPressedImage();
    }//GEN-LAST:event_jLabel1MousePressed

    public void showNormalImage() {
        //jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/button_connect_to_zeppelin.png")));
    }
    public void showLoadingImage() {
       // jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/loading.gif")));
    }
    public void showPressedImage() {
        //jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/button_connect_to_zeppelin_pressed.png")));
    }
    public void showConnectedImage() {
        //jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/button_connect_to_zeppelin_connected.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
